version: "3.8"
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN
      - GOOGLE_API_KEY
      - OWM_API_KEY
      - WOLFRAM_API_KEY
      - TWITTER_API_KEY
    env_file: docker-env.env
