version: "3.8"
services:
  bot:
    build: .
    container_name: slashbot-reborn
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DEVELOPMENT_MODE=false
    volumes:
      - .:/bot
      - ~/.ssh:/home/user/.ssh:ro
