version: "3.8"
services:
  bot:
    build: .
    container_name: slashbot
    env_file:
      - .env
    environment:
      - DEVELOPMENT_MODE=true
    volumes:
      - .:/bot
      - ~/.ssh:/home/user/.ssh:ro
