name: slashbot
channels:
  - conda-forge
dependencies:
  - unidecode~=1.3.6
  - python-dateutil~=2.8.2
  - prettytable~=3.6.0
  - watchdog~=2.2.21
  - black~=23.1.0
  - pylint~=2.15.10
  - openai~=0.26.4
  - pre-commit~=3.0.3
  - pip~=22.3.1
  - python~=3.11
  - isort~=5.12.0
  - pip:
    - rule34~=1.8.1
    - wolframalpha~=5.0.0
    - disnake~=2.7.0
    - pyowm~=3.3.0