[tool.black]
line-length = 120
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.pylint.design]
max-attributes = 15
max-locals = 20

[tool.pylint.format]
good-names = [
    "i",
    "j",
    "k"
]

[tool.pylint.messages_control]
disable = [
    "import-error",
    "wrong-import-position",
    "line-too-long",
]
