
[tool.poetry]
name = "slashbot"
version = "3.2.1"
description = ""
authors = ["Edward J. Parkinson"]
readme = "README.md"
packages = [{include = "slashbot"}]

[tool.poetry.dependencies]
python = "^3.11"
unidecode = "1.3.6"
prettytable = "3.6.0"
openai = "0.27.0"
rule34 = "1.8.1"
wolframalpha = "5.0.0"
disnake = "2.8.1"
pyowm = "3.3.0"
requests = "2.28.1"
sqlalchemy = "2.0.16"
dateparser = "^1.1.8"
tiktoken = "^0.4.0"
watchdog = "^3.0.0"
geopy = "^2.3.0"
gitpython = "^3.1.37"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ipython = "^8.13.2"
pre-commit = "^3.3.3"
isort = "^5.12.0"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.pylint.design]
max-attributes = 15
max-locals = 20

[tool.pylint.format]
good-names = [
    "i",
    "j",
    "k"
]

[tool.pylint.messages_control]
disable = [
    "import-error",
    "wrong-import-position",
    "line-too-long",
]
