
[tool.poetry]
name = "slashbot"
version = "4.1.2"
description = ""
authors = ["Edward J. Parkinson"]
readme = "README.md"
packages = [{ include = "slashbot" }]

[tool.poetry.dependencies]
python = "^3.11"
unidecode = "1.3.6"
prettytable = "3.6.0"
openai = "0.27.0"
rule34 = "1.8.1"
wolframalpha = "5.0.0"
disnake = "2.8.1"
pyowm = "3.3.0"
requests = "2.28.1"
dateparser = "^1.1.8"
tiktoken = "^0.4.0"
watchdog = "^3.0.0"
geopy = "^2.3.0"
gitpython = "^3.1.37"
pyspellchecker = "^0.7.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ipython = "^8.13.2"
pre-commit = "^3.3.3"
isort = "^5.12.0"
sqlalchemy = "^2.0.23"
ruff = "^0.1.6"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 120
indent-width = 4
target-version = "py311"


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
